### ISSUE TITLE
Possible wrong length of user-information field

### ISSUE THREAD

**Issue by 6006l1k** [Gurux/GXDLMSDirector#3]
The program sends request (High Level Security with secret):
`10:14:06 Send AARQ request
7E A0 61 02 51 21 10 99 17 E6 E6 00 60 52 A1 09 06 07 60 85 74 05 08 01 01 8A 02 07 80 8B 07 60 85 74 05 08 02 02 AC 08 80 06 32 32 32 32 32 32 BE 10 04 0E 01 01 1D 75 39 3D 64 43 40 5B 5B 33 2A 54 29 63 2C 54 27 40 62 74 59 24 6F 54 34 4D 78 61 69 4B 00 00 06 5F 1F 04 00 00 7E 1F FF FF 69 CE 7E`

I try to parse user-information field and seem's like length is invalid value:
![image](https://cloud.githubusercontent.com/assets/814182/13313413/b847c9ba-dbae-11e5-8317-1d1376bf3baa.png)

I'm using latest version DLMSDirector 8.0.0.8.

**Comment by gurux01** [comment]
Hi,

You are right. We made some changes for GMAC. We have fixed this. We will release new version during this week.

BR,

Mikko

**Comment by gurux01** [comment]
Hi,

We have fixed this. New version is on GitHub and new version fro GXDLMSDirector is avaialble.

BR,

Mikko
