### ISSUE TITLE
Block number don't reset

### ISSUE THREAD

**Issue by 6006l1k** [Gurux/GXDLMSDirector#4]
The block number don't reset, if previous GetObjects ended with an error
> 11:19:13 --- Collecting objects. ---
> 11:19:13 Collecting objects
> `7E A0 1A 02 51 61 32 F0 01 E6 E6 00 C0 01 81 00 0F 00 00 28 00 00 FF 02 00 94 9E 7E`
> 11:19:13 Received data
> `7E A0 33 61 02 51 52 0F 35 E6 E7 00 C4 02 81 00 00 00 00 01 00 1C 01 01 02 04 12 00 08 11 00 09 06 00 00 01 00 00 FF 02 02 01 01 02 03 0F 01 16 01 00 9E 7D 7E`
> System.Exception: GetObjects failed. Invalid Block number. It is 1 and it should be 3.
>   in GXDLMSDirector.MainForm.ReadDevice(GXDLMSDevice dev) in C:\Projects\GXDLMSDirector\Development\MainForm.cs:string 1345
>   in GXDLMSDirector.MainForm.Read(Control sender, Object[] parameters) in C:\Projects\GXDLMSDirector\Development\MainForm.cs:string 1461`

**Comment by gurux01** [comment]
Hi,

We fixed this and updated new version from GXDLMSDirector. We will update source codes also.
