### ISSUE TITLE
Invalid attributes numbers

### ISSUE THREAD

**Issue by 6006l1k** [Gurux/GXDLMSDirector#5]
Invalid attribute numbers of "Max Window Size Receive" and "Max Info Length Transmit":

https://github.com/Gurux/GXDLMSDirector/blob/e919643164ee1631d4547b28e53aa147e14ecf3b/Development/Views/GXDLMSHdlcSetupView.cs#L246

https://github.com/Gurux/GXDLMSDirector/blob/e919643164ee1631d4547b28e53aa147e14ecf3b/Development/Views/GXDLMSHdlcSetupView.cs#L292

**Comment by gurux01** [comment]
Hi,
Thanks from this information. 
This is fixed and new version is at GitHub.
